<script lang="ts">
	import Title from '$lib/Title.svelte';
	import FlowArrow from './FlowArrow.svelte';
	import LargeImage from '$lib/LargeImage.svelte';
	import LinkButton from '$lib/LinkButton.svelte';
	// images
	import emailImg from '$lib/assets/email/email.png';
	import startBtnImg from '$lib/assets/email/start-btn.png';
	import modalImg from '$lib/assets/email/modal.png';
	import webImg from '$lib/assets/email/web.png';
	import confirmImg from '$lib/assets/email/confirm.png';
</script>

<Title
	title="Email Verification"
	description="Husky Cycling Club's email verification system"
	image={emailImg}
/>
<div class="mx-8 flex flex-col gap-4 md:mx-40">
	<h3>Fast and Secure</h3>
	<p>
		Because we plan meeting locations in our Discord server, we ensure that only students at our
		university can access sensitive message channels.
	</p>
	<p>
		Previously, new members had to fill out a Google Form while signed into their university Google
		account. It would then take up to a week for an officer to manually grant them elevated
		permissions in our Discord server. The new system grants members immediate access to our Discord
		server if they have a current university email address.
	</p>
	<p>
		What used to take days now takes seconds, improving our ability to engage with prospective
		members.
	</p>

	<h3>Serverless Architecture</h3>
	<p>
		I leverage Cloudflare Workers for high performance, low-cost back-end hosting. Serverless
		Workers don't require provisioning, and automatically scale from 0 daily users up to peak usage
		that may occur during club meetings. JWT-based session management averts the need for persistent
		storage, isolating requests from failures and allowing them to be served at the closest
		Cloudflare server to the user.
	</p>

	<h3 class="mt-6">Verification Flow</h3>
	<p>
		This flowchart depicts the user-facing steps and back-end processing that makes up the email
		verification system.
	</p>
</div>

<div class="mx-auto my-18 w-3/4 text-center sm:w-2/3 md:w-1/2">
	<LargeImage image={startBtnImg} caption="Users begin by selecting 'Verify with NetID'" />
	<FlowArrow />

	<div class="mx-15">
		<LargeImage
			image={modalImg}
			caption="Users enter their email address while still signed into Discord"
		/>
	</div>
	<p>
		On submission, Discord's servers POST the users's email address, name, and Discord account ID to
		my server. Because these requests are signed, my server can use its key to ensure that the
		request originated from Discord and that its payload has not been altered. This way, I can
		safely attribute the user's Discord ID with their email address.
	</p>
	<FlowArrow />

	<LargeImage image={emailImg} caption="Users receive an email containing a verification link" />
	<p>
		The URL's query string has a JWT which contains the user's Discord ID and an expiration date.
		Because it is also signed, my server can later verify that the JWT was generated by itself and
		that the payload is authentic.
	</p>
	<FlowArrow />

	<LargeImage
		image={webImg}
		caption="A page on our website has a button which grabs the JWT from the query string and POSTs it to my server"
	/>
	<p>
		If the JWT is valid, my server will make the Discord API requests necessary to grant the user
		elevated permissions in our Discord server.
	</p>
	<FlowArrow />

	<LargeImage
		image={confirmImg}
		caption="Verification is complete! Users receive a confirmation message."
	/>
</div>

<div class="mx-8 flex flex-col gap-4 md:mx-40">
	<h3>Links</h3>
	<div class="flex flex-wrap gap-3">
		<LinkButton url="https://github.com/roy-rishi/hcc-bot" name="GitHub Repo" />
		<LinkButton url="https://www.huskycyclinguw.com/verify?token=test-of-invalid-token" name="Live Demo: Invalid Token" />
	</div>
</div>
